version: '3'

services:
  nginx_service:
    image: nginx
    container_name: nginx_1
    ports:
      - 80:8000
    volumes:
       - ./:/app
       - .deploy/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
       - static_volume:/app/static
       - templates_volume:/app/templates
    expose:
      - 80
    depends_on:
      - web_service

  web_service:
    container_name: web_1
    restart: always
    env_file:
      - .env
    build:
        context: ./
        dockerfile: .deploy/local/api/Dockerfile
    command: >
      bash -c "flask db upgrade && chmod 755 -R /app/static && gunicorn -w 3 -b 0.0.0.0:8000 wsgi:app"
    volumes:
      - ./:/app
      - static_volume:/app/static
      - templates_volume:/app/templates
    expose:
      - 8000
    depends_on:
      - postgres_service
      - redis_service

  postgres_service:
    container_name: postgres_1
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - .deploy/local/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis_service:
    container_name: redis_1
    image: redis
    command: redis-server --requirepass ${CACHE_REDIS_PASSWORD}
    env_file:
      - .env

volumes:
  postgres_volume:
    driver: local
  static_volume:
  templates_volume:
